# Base configs
baseurl: "http://agodinezaguilar.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Alfonso Godínez Aguilar"
subtitle: "See the world through my eyes!"
author: "Alfonso Godínez Aguilar"
header:
 title: "Photography"
 subtitle: "by Alfonso Godínez Aguilar"
footer:
 name: "hey there, my name is alfonso"
 bio: "I am a student at Harvard College studying Chemical & Physical Biology and Latinx studies. I love capturing the beauty of our world through both digital and film photography."
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/alfonsojgodinez"
  linkedin: "https://www.linkedin.com/in/alfonsojgodinez/"
